import type { OrderRecord } from "@/lib/types";

export const mockOrders: OrderRecord[] = [
  {
    id: "order-1",
    created_at: "2026-04-27T09:30:00.000Z",
    pid: "P-001",
    process: "복층",
    item_code: "DG-001",
    item_name: "복층유리",
    width: 1200,
    height: 1800,
    quantity: 30,
    area_pyeong: 19.6,
    request_no: "REQ-001",
    no: "1",
    customer: "OO건설",
    site: "청주A현장",
    line: "2라인",
    registrant: "김대리",
    status: "등록",
    memo: "긴급 요청",
    is_favorite_source: false
  },
  {
    id: "order-2",
    created_at: "2026-04-27T10:20:00.000Z",
    pid: "P-002",
    process: "강화",
    item_code: "DG-002",
    item_name: "강화유리",
    width: 900,
    height: 1200,
    quantity: 20,
    area_pyeong: 5.88,
    request_no: "REQ-002",
    no: "2",
    customer: "청주창호",
    site: "오창B현장",
    line: "1라인",
    registrant: "이주임",
    status: "진행",
    memo: "샘플 시공",
    is_favorite_source: false
  },
  {
    id: "order-3",
    created_at: "2026-04-27T11:10:00.000Z",
    pid: "P-003",
    process: "복층",
    item_code: "DG-003",
    item_name: "로이복층유리",
    width: 1000,
    height: null,
    quantity: 15,
    area_pyeong: null,
    request_no: "REQ-003",
    no: "3",
    customer: "충북유리",
    site: "진천C현장",
    line: "3라인",
    registrant: "박사원",
    status: "확인필요",
    memo: "세로 규격 확인 필요",
    is_favorite_source: true
  }
];
